### ISSUE TITLE
Full stop required after URL

### ISSUE THREAD

**Issue by dmiddleton** [dragonfly-science/mpi-latex-templates#11]
Same example as issue #10, just need a full stop added after the URL.

**Comment by edwardabraham** [comment]
Hiya. The easiest way to modify this is so that a reference *always* finishes in a fullstop. There are various exceptions to this in the APA style, but this approach looks reasonable in my test examples. Any thoughts @katrin?

**Comment by katrin-berkenbusch** [comment]
Yes, that’s a good way forward. I can’t think of any reference right now that wouldn’t need a full stop at the end.
