### ISSUE TITLE
placement of front cover info

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/mpi-latex-templates#24]
Suze has asked for the front cover info to be moved down by about 1 cm.

**Comment by katrin-berkenbusch** [comment]
For the FAR template.

**Comment by dmiddleton** [comment]
Comparing the template output of a recent FAR (2021/37) with the  manually adjusted version that MPI have published, it seems that the title starts in the right place on the page, but the spacing between items has been increased such that the date is closer to the images. I think this should be achievable by adding vfills

**Comment by dmiddleton** [comment]
A minipage environment was also required to get the vfills to take effect. I _think_ this achieves what is being requested so will bump the version number to 1.27 and add this to the kahawai.io dockers for further verification...

**Comment by dmiddleton** [comment]
For FAR 2021/37 the version 1.27 template produces front cover info that is close, but not identical, to MPI's manually adjusted version. Given the opening comment on this issue, it may be that MPI wish to take different approaches in some situations (e.g. with varying title and author list lengths) so will leave this issue open for now

**Comment by dmiddleton** [comment]
Closing this for now, but see #38 about the title font scaling. May need to reopen this if we ever get better quality title page images from MPI.
