### ISSUE TITLE
splitting of words across lines

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/mpi-latex-templates#25]
the current set up allows words to be split incorrectly across lines; e.g., dens-ity  instead of den-sity or densi-ty.

Would it be possible to prevent this type of splitting?

**Comment by katrin-berkenbusch** [comment]
or does it require going through the final report document and using \mbox{} on the offending words?

**Comment by yvanrichard** [comment]
I would have thought LaTeX would get this right. What are the rules? I would have thought dens-ity is the right one.

**Comment by katrin-berkenbusch** [comment]
For density, the correct splitting would be den-sity. I have a number of other incorrect splits in the FAR for AKI, and also correct ones. I guess the options are to go through the final document and fix the words via \mbox or to set up the template to not split words across lines?

**Comment by katrin-berkenbusch** [comment]
This issue also applies to the references, e.g., I have a split of "Zealand" as "New Zeal- and" - the correct split would be "Zea-land".

**Comment by yvanrichard** [comment]
While dealing with the NEFD report which doesn't do word splits, I discovered that one can prevent any word split with

```
\usepackage[none]{hyphenat}
```

**Comment by katrin-berkenbusch** [comment]
Yes, I saw that online, but does it allow justified text?

**Comment by katrin-berkenbusch** [comment]
Thanks to @yvanrichard for sending the link for this approach, it did the trick -

\tolerance=1
\emergencystretch=\maxdimen
\hyphenpenalty=10000
\hbadness=10000

**Comment by katrin-berkenbusch** [comment]
interesting enough, it solved other justification problems at the same time.

**Comment by dmiddleton** [comment]
I've been using this solution (https://github.com/dragonfly-science/mpi-latex-templates/issues/25#issuecomment-717566745) for a while: is it worth adding to the template so it becomes a default?

**Comment by dmiddleton** [comment]
@yvanrichard 's solution is now part of the template (from v1.28)

**Comment by katrin-berkenbusch** [comment]
It seems that this solution does not help with splits in captions. Any thoughts?

**Comment by yvanrichard** [comment]
Bummer. Do you have an easy example to play with locally, @katrin-berkenbusch?

**Comment by katrin-berkenbusch** [comment]
Yes, looks at dragonfly-science/PAU2019-01-PAU2-ASSMT:

In īnput.Rnw' there is a figure caption ({fig:catchcircle}, Figure 5 in the PDF) that has word getting split over a line in a bad way: "....same time period (right-hand side). Stat-
istical reporting areas...".

**Comment by katrin-berkenbusch** [comment]
Using the`\mbox{}' approach in the meantime. ; )

**Comment by yvanrichard** [comment]
It appears that the image docker.dragonfly.co.nz/dragonverse-18.04 that you're using in that report is using an old latex template (v1.25) so there's plenty of word breaking happening, not just in the caption.
I added the fix for now to assessment_report.tex and it seems to be working.

**Comment by katrin-berkenbusch** [comment]
Thanks heaps @yvanrichard I am sorry, I didn't even think to check that.
