### ISSUE TITLE
full landscape for landscape pages

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/mpi-latex-templates#26]
The MPI editor Suze has requested that landscape pages are "fully landscape", meaning that the page number and footer are not in portrait orientation.  

I've had a go at correcting this format for the AKI FAR, looking up various option in the LaTeX fora: I ended up using \usepackage{geometry},  but I am losing the page number and header.

I am raising the issue here in case it can be addressed via the templating.  It would apply to FARs and AEBRs.
Any tip welcome.

Ps: I am also using \usepackage{pdflscape} instead of \usepackage{lscape}, as the former is easier for online reading.

**Comment by katrin-berkenbusch** [comment]
fixed by @lauratboyer !

**Comment by katrin-berkenbusch** [comment]
Laura's approach:
> add the library (part of the KOMA-script family):

`\usepackage[usegeometry]{typearea}`
 instead of using pdflscape to create the landscape page, define a new command based on koma-script to set up the landscape page:  

```
\newcommand*{\uselandscape}{%
  \clearpage
  \KOMAoptions{paper=landscape,DIV=current}%switch to landscape
  \newgeometry{% geometry settings for landscap
    left=0.8125in, right=1in, top=2.5cm, bottom=1.25in, footskip=0.875in
  }%
  \fancyhfoffset{0pt}% recalculate head and foot width for fancyhdr
}
```

> going back to portrait, call on another function that sets back the margins right:

```
\newcommand*{\useportrait}{ % To use after calling \uselandscape to go back to initial conditions
 \clearpage
  \KOMAoptions{paper=portrait,DIV=current}%switch to portrait
  \loadgeometry{defaultgeo}
  \fancyhfoffset{0pt}% <- recalculate head and foot width for fancyhdr
}
```
for the margins, save the current geometry at the start of the document and reload it later:
`\savegeometry{defaultgeo}`

- it then gets reloaded when switching back to portrait mode using 
`\loadgeometry{defaultgeo}`

**Comment by dmiddleton** [comment]
An alternative approach, used for the PSB2019-06 AEBR, is setup as:

```
% https://tex.stackexchange.com/questions/9071/how-to-translate-and-rotate-the-heading-of-landscaped-pages
\fancypagestyle{lscapefoot}{%
\fancyhf{} % clear all header and footer fields
\fancyfoot[LE]{%
\begin{textblock*}{1.0\textheight}[0,1](190mm,271mm){\rotatebox{90}{\rule{247mm}{0.4pt}}}\end{textblock*}
\begin{textblock*}{0.7\textwidth}[0,1](192mm,271mm){\rotatebox{90}{\sffamily\scriptsize\thepage\ {\normalsize$\bullet$}\ \footertitle}}\end{textblock*}
\begin{textblock*}{0.3\textwidth}(192mm,24mm){\rotatebox{90}{\sffamily\scriptsize Fisheries New Zealand}}\end{textblock*}}
\fancyfoot[LO]{%
\begin{textblock*}{1.0\textheight}[0,1](190mm,271mm){\rotatebox{90}{\rule{247mm}{0.4pt}}}\end{textblock*}
\begin{textblock*}{0.3\textwidth}[0,1](192mm,271mm){\rotatebox{90}{\sffamily\scriptsize Fisheries New Zealand}}\end{textblock*}
\begin{textblock*}{0.7\textwidth}(192mm,24mm){\rotatebox{90}{\sffamily\scriptsize\footertitle\ {\normalsize$\bullet$}\ \thepage}}\end{textblock*}}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}}

```
then used as:

```
\newgeometry{hmargin=2.5cm,vmargin=2.5cm}
\thispagestyle{lscapefoot}
\pagestyle{lscapefoot}
\begin{landscape}
...
\end{landscape}
\restoregeometry
\pagestyle{plain}
```

However, this is clearly more verbose than Laura's version.

**Comment by dmiddleton** [comment]
v1.55 of the template adds a "full landscape" (`flandscape`) environment, i.e.:
```
\begin{flandscape}
...
\end{flandscape}
```
This simplifies (I hope) the production of landscape pages with rotated footers. In practice, I had to use the second approach because the `typearea` package doesn't function correctly when used in an environment.

The positioning of the rotated footers could probably be implemented in a more elegan fashion, but this seems to work
