### ISSUE TITLE
tables in 10 pt font

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/mpi-latex-templates#28]
We are consistently getting requests from the MPI editor to have the table text in 10 pt font.

**Comment by dmiddleton** [comment]
This can be fixed within individual documents:
- for hard coded LaTeX tables, use `\fontsize{10}{12}\selectfont` before `\begin{tabular}`
- for kable tables use `kable_styling(font_size = 10)`

**Comment by katrin-berkenbusch** [comment]
thanks, that’s good to know.

**Comment by katrin-berkenbusch** [comment]
I just had this request again from he MPI editor (31 Oct 2022), so will give it a shot.

**Comment by dmiddleton** [comment]
The `mpi-far.text` and `mpi-aebr.text` examples now illustrate setting 10pt font for the tables (see the appendices). `mpi-tables.rnw` illustrates production of tables with R's `kableExtra` package, including setting the font size
