### ISSUE TITLE
required update for the AEBR and FAR templates?

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/mpi-latex-templates#30]
These report types now need to include the author's affiliations at footnotes at the bottom of the self-cite page (first page of Executive Summary).

Maybe this change doesn't need to be templated? Here is what I did for a recent AKI FAR, when all authors had the same affiliation:

\textbf{Neubauer, P.\footnote{Dragonfly Data Science, New Zealand.}; Damodaran, D.\footnotemark[1]; Berkenbusch, K.\footnotemark[1](2021). Bivalve abundance in relation to sediment properties across northern North Island.}

**Comment by katrin-berkenbusch** [comment]
from MPI editor -  "When there are many authors from the same organisation (I take that as more than 3), it is acceptable to put the footnote number after the first author only and then add wording as below
 
All authors: Dragonfly Data Science, New Zealand."

**Comment by dmiddleton** [comment]
I have added a somewhat hacky solution to this from v1.30. It requires a different format for the `\author{}` specification - see the `mpi-far.tex` example. However, it _shouldn't_ break old versions too badly. When defining the `affiliation=` for an author you should now use either `\newaffiliation{<tag>}{<description>}` (the first time an institution is mentioned) or `\useaffiliation{<tag>}` (for subsequent autores with the same institution).

**Comment by dmiddleton** [comment]
There may be alternative/better approaches. The widely cited `authblk` package seems to be incompatible with our template. The `svjour3` document class looks like it has a `\institute{}` command that provides footnotes (noted in an exchange [here](https://tex.stackexchange.com/questions/597627/paragraph-ended-before-institute-was-complete-can-not-fix))

**Comment by dmiddleton** [comment]
One known bug is that including a comma in the `<description>` causes the build to fail. This may be due to the problem described in this [stackexchange thread](https://tex.stackexchange.com/questions/414685/paragraph-ended-before-name-was-complete). This is definitely less than ideal - given the expectation that the footnotes will contain names _and_ addresses, so needs further attention soon.

**Comment by dmiddleton** [comment]
Version 1.31 adds `\addrsep{}` which is used within the institution `<description>` and (i) doesn't cause the build to fail and (ii) adds a comma and space in the footnote. Possibly not the most elegant solution, but solves the immediate problem.

**Comment by dmiddleton** [comment]
The solution, while inelegant, is working, so closing this issue for now
