### ISSUE TITLE
May 2022 updates to the FAR and AEBR formats

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/mpi-latex-templates#35]
MPI has forwarded an update to the formats of both reports in the form of a MS Word document.

Changes are required to the front cover, the inside front cover, and the authors' affiliation.

**Comment by katrin-berkenbusch** [comment]
Any thoughts @finlay ?

**Comment by katrin-berkenbusch** [comment]
![NZGovt-logo-expanded-wordmark](https://user-images.githubusercontent.com/1176505/169924871-75b3803e-c4c6-4b98-914e-21389e125b08.png)

Here is the logo.

**Comment by katrin-berkenbusch** [comment]
FRONT COVER
Please remove the current govt logo and replace with the attached version in the position shown on the word doc front cover. As an aside, is it possible to shift the fishNZ logo down a bit as shown on the attached doc?
 
Note: There are existing style differences on the front cover between the two report types for the front cover:
– FAR title is in Arial black bold between 16 and 24 pt depending on title length, spacing is 11 pt Arial between lines, and remainder of front cover text is Arial 11 pt – with bold for month and year
– AEBR title is in Arial Narrow black between 16 and 24 pt depending on title length, spacing is 12 pt Arial Narrow between lines, and remainder of front cover text is Arial Narow 12 pt – with bold for month and year.

INSIDE FRONT COVER
For the inside front cover, please replace the current text with all the text given on the second page of attached word doc (Arial 10 pt). Please ensure the email and web links are included and complete the citation required ....(in the layout style shown on the word doc inside front  cover).

**Comment by katrin-berkenbusch** [comment]
The MS Word example is here - https://docs.google.com/document/d/1kv_i8PO0zuWkJtp3DvLNVPByV3wiXIab/edit

On the front cover of this example, there is overlap between the blue vertical panel and the Fisheries NZ logo. I have sent a query to the MPI editor to confirm that this overlap is how it should look.

**Comment by edwardabraham** [comment]
Thanks very much Katrin. Conditional font-size based on title-length should be a fun challenge for me !

**Comment by edwardabraham** [comment]
Is there a time frame for this (other than ASAP!).

**Comment by katrin-berkenbusch** [comment]
We've got one FAR ready for publication that is waiting for the template update (it already has its publication details assigned), another one is not far off. So "asap" sums it up.  ; )

**Comment by katrin-berkenbusch** [comment]
Thanks @edwardabraham

**Comment by katrin-berkenbusch** [comment]
Just had an update from MPI re the placement of the Fisheries NZ logo: "It should butt against the blue banner. A slight shift to the left from your usual layout".

**Comment by katrin-berkenbusch** [comment]
[AEBR-283-R-Code-For-Standardised-Grids-For-New-Zealand-Marine-Science-Outputs-4277.pdf](https://github.com/dragonfly-science/mpi-latex-templates/files/8758731/AEBR-283-R-Code-For-Standardised-Grids-For-New-Zealand-Marine-Science-Outputs-4277.pdf)

Here is a PDF example (of a published report) Suze Baird sent.

**Comment by katrin-berkenbusch** [comment]
Just flagging that the cover images still differ between the AEBR and the FAR.

**Comment by katrin-berkenbusch** [comment]
Please note that there are not author affiliations Iso no footnote number) on the front cover and inside front cover. I just had that confirmed by Suze Baird at MPI.

**Comment by dmiddleton** [comment]
I have made a bit of a start on these updates. I'm going to start a few separate issues to keep track of some distinct changes required.

**Comment by dmiddleton** [comment]
All done, I think, other than #38 (unless we receive better quality cover images)
