### ISSUE TITLE
change in font when using math mode

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/mpi-latex-templates#4]
It seems that the font of numbers is changed in some cases when $ signs indicate math mode. I've seen it in the bivalve report and in the mmra.

**Comment by edwardabraham** [comment]
I am going to close this issue. I have put some numbers in the example MPI FAR but I can't see anything wrong with them. reopen if it is a problem, and perhaps attach a screenshot that illustrates the problem.

**Comment by katrin-berkenbusch** [comment]
Yes, that's what Marianne has picked up on (and Marine for AKI reports).

**Comment by dmiddleton** [comment]
It appears we can address this using the `mathspec` package. I have this working in the kahawai build for now.

**Comment by edwardabraham** [comment]
Wow! progress on a six year old issue.

**Comment by dmiddleton** [comment]
The use of `mathspec` (https://ctan.org/pkg/mathspec?lang=en) is implemented in v1.55 of the template. This aims to typeset maths in the normal (Times New Roman) font used in the templates. There are some simple examples in `mpi-far.tex`.

The `mathspec` documentation discusses various issues with typesetting maths in normal fonts; these may be relevant in some cases.
