### ISSUE TITLE
cited references not in consecutive order in the text 

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/mpi-latex-templates#40]
It seems that `\citep{}` puts the references in alphabetical not consecutive order in the PDF.  This change may be due to APA style, but needs to be swapped to have them in consecutive order.

**Comment by katrin-berkenbusch** [comment]
Any chance of someone to look into this issue within the next week or so? maybe @richardmansfield ?

**Comment by richardmansfield** [comment]
For once it was easy! It's running now, and will be in
dragonflyscience/dragonverse-22.04:2022-08-02 soon.

**Comment by dmiddleton** [comment]
Out of curiosity:

@richardmansfield , does the `sortcites=false` approach mean that the user is responsible for putting the citations into chronological order in their code?

@katrin-berkenbusch I assume this was another of the ongoing minor tweaks that MPI seem to be requesting each report submission (i.e., rather than defining the required format completely once and for all?)

**Comment by katrin-berkenbusch** [comment]
@dmiddleton Hi there, no, having the references in consecutive order in the text has remained consistent and was included again in the MPI template update this year.

**Comment by katrin-berkenbusch** [comment]
awesome.

**Comment by dmiddleton** [comment]
> @dmiddleton Hi there, no, having the references in consecutive order in the text has remained consistent and was included again in the MPI template update this year.

Thanks - looking back I see it was the update to 22.04 when this changed to alphabetical sorting in the FAR example. Good spotting!

**Comment by richardmansfield** [comment]
So does "consecutive" mean "chronological" here, or not? In my mind those words have different meanings. Damn, github lost one of my email replies.

**Comment by dmiddleton** [comment]
> So does "consecutive" mean "chronological" here, or not? In my mind those words have different meanings. Damn, github lost one of my email replies.

That was my interpretation. But I may be wrong ... @katrin-berkenbusch will confirm!

**Comment by katrin-berkenbusch** [comment]
Yes, 

Sorry, I should’ve been clearer, “chronological" is the word.

Here’s an example of how references look in a FAR PDF at the moment: "Brander et al. 2013, Jutfelt et al. 2018, Lefevre 2016, Lefevre et al. 2018”,
but they should be listed in this order:
"Brander et al. 2013, Lefevre 2016, Jutfelt et al. 2018, Lefevre et al. 2018”.

[Hm, that’s a tricky example with the alphabetical 2018 reference-ordering thrown in, although it seems to apply automatically if the bib reference is entered correctly].

**Comment by richardmansfield** [comment]
The sample doc works for me now, finally. @katrin-berkenbusch, give `dragonflyscience/dragonverse-22.04:2022-08-04` a try when you're ready.

Weirdly enough, APA is using slightly different sorting orders for citations and the reference list. The very newest biblatex now has some support for that. I tried to backport that stuff to the version in ubuntu 22.04, but it was just too hard :(. Instead I have overridden `\printbibliography`. It works on the sample FAR but might have some side effects I guess.

**Comment by katrin-berkenbusch** [comment]
Thanks @richardmansfield that sounds great, I'll give it a try.  Hopefully I'll catch any side effects. :-)

**Comment by katrin-berkenbusch** [comment]
it worked like a treat, I haven't found any side effects yet. Thank you @richardmansfield

**Comment by richardmansfield** [comment]
Oh sorry, yes I guess I just removed sorting. That's just me not realising
that consecutive == chronological.
