### ISSUE TITLE
template update - comma-separated author names on the front cover

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/mpi-latex-templates#43]
The list of author names on the front cover needs to have a comma after each author's surname (except the last one).

Any thoughts on how to achieve this change?

An example of the current name list is
`\author{K. Berkenbusch, \and T. Hill-Moana, \and P. Neubauer}`

which appears as:
K. Berkenbusch
T. Hill-Moana
P. Neubauer

but should be: 
K. Berkenbusch,
T. Hill-Moana,
P. Neubauer

**Comment by dmiddleton** [comment]
Solved by @richardmansfield: https://github.com/dragonfly-science/mpi-latex-templates/commit/a2005cf9cff665246e94e66122132a000603cab7
