### ISSUE TITLE
listed references

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/mpi-latex-templates#8]
The MPI editor requested for the reference list that:
- for authors with several initials, the letters are not separated by a space;
- there is no comma between the journal title and volume number;
- there is a colon instead of a comma between the journal volume/number and the page numbers.

Titles of books, unpublished reports and theses should not be in italics, e.g.,  Currey, R. J. C.; Boren, L. J.; Sharp, B. R.; Peterson, D. (2012). A risk assessment of threats to Maui’s dolphins. 51 p. Wellington, New Zealand: Ministry for Primary Industries and Department of Conservation.
IUCN (2016). International Union for Conservation of Nature Red List of threatened species. Version 2016-3. 

For books, the publisher name should be placed in front of the location (also for DoC reports and similar), e.g., see above for the risk assessment.

**Comment by edwardabraham** [comment]
Done. Available in `docker.dragonfly.co.nz/dragonfly-reports-17.04:2017-11-28`

**Comment by katrin-berkenbusch** [comment]
Thesis titles seem to be in italics, with species name in roman font...? see Davidson in the mmra report.
Also IUCN reference in the same report, Mitchell et al.
Same for Richard & Abraham (2016) and (2017), including upper case in the 2016 one.

**Comment by katrin-berkenbusch** [comment]
These and some other less frequently-used publication types have the titles in italics

**Comment by katrin-berkenbusch** [comment]
Seems to also be that chapter titles are in italics.

**Comment by edwardabraham** [comment]
Here is a list of all the types in our bibliography:

- 1052 @Article
- 266 @Unpublished
- 147 @Book
-  92 @InCollection
-  54 @Misc
-  17 @PhDThesis
-  14 @InProceedings
-   7 @Manual
-   3 @TechReport
-   1 @incollection
-   1 @Conference

**Comment by edwardabraham** [comment]
Interesting. Chapter titles. Hadn't thought about that. About this point I start wanting to tear my hair out (but I haven't got any!)

**Comment by katrin-berkenbusch** [comment]
I’ve been tearing away for both of us…it’s so pedantic.

**Comment by edwardabraham** [comment]
Sorry. I can't find any Chapter titles? What were you referring to there (the more specific the better!).

**Comment by katrin-berkenbusch** [comment]
Sorry, I may have meant this one in the mammal estimates, not a chapter -
Ridout, M.; Demetrio, C.G.B.; Hinde, J. (1998). Models for count data with many zeros. In: Proceedings
of the XIXth International Biometric Conference. International Biometric Society, Washington. Pp
179–192.

**Comment by edwardabraham** [comment]
One of those pesky collections. Hopefully, I have fixed them ...
