### ISSUE TITLE
self-cite author info

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/mpi-latex-templates#9]
The listing of authors in the self-cite information needs to be the family name, followed by the initials for each authors, e.g., 
"Thompson, F.N.; Abraham, E.R.; Berkenbusch, K. (2017)".

I can fix it, I am just raising the issue as a note for the template.

**Comment by dmiddleton** [comment]
APA only allows one middle initial as per my comment on the commit

**Comment by edwardabraham** [comment]
This is weird. If I use this as my source
```
% Authors must be listed with their full names separated by \and.           
\author{John A. G. Smith \and Jane E. Smith}                                                                             
```
I get the following output:
"Smith, J.A.G.; Smith, J.E. (2015). An example Fisheries Assessment Report (FAR)."

What does your author line look like?

**Comment by dmiddleton** [comment]
I had

`\author{David A.J. Middleton \and Sam A. Middleton \and Oliver L. Wilson}`

but when changed to 

`\author{David A. J. Middleton \and Sam A. Middleton \and Oliver L. Wilson}`

it works as intended.  So having initials separated by a space is important, it seems.  But solved, so excellent news.
